### ISSUE TITLE
UIWebView is rejected by Apple and needs to be updated 

### ISSUE THREAD

**Issue by marcorivm** [nwrman/cordova-plugin-conekta#2]
On line 28 we are using UIWebView which has been deprecated
https://github.com/nwrman/cordova-plugin-conekta/blob/97d9b451af716221178efc8e606a07a8a52695a5/src/ios/Conekta/Conekta.m#L28

> Updating Apps that Use Web Views
> December 23, 2019
> 
> If your app still embeds web content using the deprecated UIWebView API, we strongly encourage you to update to WKWebView as soon as possible for improved security and reliability. WKWebView ensures that compromised web content doesn’t affect the rest of an app by limiting web processing to the app’s web view. And it’s supported in iOS and macOS, and by Mac Catalyst.
> 
> The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.

This needs to be updated to use WKWebView for new apps to be accepted by apple

**Comment by bjdose** [comment]
Hello @marcorivm could you resolve this issue? I'm try to deal with it but I don't know how to resolve it

**Comment by marcorivm** [comment]
> Hello @marcorivm could you resolve this issue? I'm try to deal with it but I don't know how to resolve it

I uploaded a PR, we just got an app approved and working using those changes
